# This is a config file for the license plate recognition task
img_size: &im [64, 128]
time_steps: &ts 15

# training config
batch_size: 16
num_workers: 0
lr: 5.e-4
warmup: 0
epochs: 100

# data config
train:
  data_dir: "/home/ubuntu/datasets/lpr/train"
  time_steps: *ts
  img_size: *im
  aug: True
val:
  data_dir: "/home/ubuntu/datasets/lpr/val"
  time_steps: *ts
  img_size: *im
  aug: False

# model config
model:
  time_steps: *ts
  n_class: 68
  n_feat: 64
  train: True

# loss config
focal_ctc_loss:
  alpha: 0.8
  gamma: 3.0
