# This is a config file for the license plate recognition task
img_size: &im [96, 192]
time_steps: &ts 15

# training config
batch_size: &bs 32
num_workers: 0
lr: 3.e-4
warmup: 0
epochs: 100

# data config
train:
  batch_size: *bs
  tfrecord: "/home/ubuntu/datasets/lpr/train.tfrecord"
  # tfrecord: "data/val.tfrecord"
  data_aug: True
  
val:
  batch_size: *bs
  tfrecord: "/home/ubuntu/datasets/lpr/val.tfrecord"
  # tfrecord: "data/val.tfrecord"
  data_aug: False

# model config
model:
  time_steps: *ts
  n_class: 68
  n_feat: 64
  train: True

# loss config
focal_ctc_loss:
  alpha: 0.8
  gamma: 3.0
