# This is a config file for the license plate recognition task
# img_size: &im [96, 192]
img_size: &im [64, 128]
time_steps: &ts 15

# training config
batch_size: &bs 128
lr: 5.e-4
warmup: 5
epochs: 100
eval_freq: 5

# data config
train:
  batch_size: *bs
  tfrecord: "/home/ubuntu/datasets/lpr/train.tfrecord"
  # tfrecord: "data/val.tfrecord"
  data_aug: True

val:
  batch_size: *bs
  tfrecord: "/home/ubuntu/datasets/lpr/val.tfrecord"
  # tfrecord: "data/val.tfrecord"
  data_aug: False

# model config
model:
  time_steps: *ts
  n_class: 68
  n_feat: 64

# loss config
focal_ctc_loss:
  blank_id: 0
  alpha: 0.8
  gamma: 3.0

## acc: 98.53