# This is a config file for the license plate recognition task
img_size: &im [64, 128]
time_steps: &ts 15

# training config
batch_size: 32
num_workers: 1
lr: 2.e-3
warmup: 5
epochs: 100

# data config
train:
  data_dir: "/Users/haoyu/Documents/datasets/lpr/train"
  time_steps: *ts
  img_size: *im
  aug: True
val:
  data_dir: "/Users/haoyu/Documents/datasets/lpr/val"
  time_steps: *ts
  img_size: *im
  aug: False

# model config
model:
  time_steps: *ts
  n_class: 68
  n_feat: 64
  train: True

# loss config
focal_ctc_loss:
  alpha: 0.25
  gamma: 2.0
